# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "SevillaDevelopersConf "
email: "contacto@sevilladevelopers.com"
description: "Sesiones para aprender juntos"
baseurl: ""
url: "http://www.sevilladevelopers.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-61791444-1"
#googleAnalyticsTrackingId: "UA-64592177-1"
googleAnalyticsSiteUrl: "sevilladevelopers.github.io"
siteVerification: "Ay_dR1jYty54q786TpnGMfFLKf0FpgroITTnw1TmTv4"


# Organizer Info
organizerName: "Sevilla Deverlopers"
organizerAlternateName: "Grupo de desarrolladores y desarrolladoras en Sevilla"
organizerDescription: "Grupo sin ánimo de lucro cuyo objetivo es el de aprender e intercambiar conocimientos y experiencias acerca de las tecnologías de la información"
organizerEmail: "contacto@sevilladevelopers.com"
organizerLogo: ""
organizerLink: "https://www.facebook.com/groups/sevilladevelopers/"

# Head
metaKeywords: "conferencia, evento, gdg, jug, tecnologia, developers, sevilla, desarrollo, event"
twitterAccount: "@SevillaDevelope"
socialImageSrcGooglePlus: "/img/seo/share-GP-big.png"
socialImageSrcTwitter: "/img/seo/share-TW-big.png"
socialImageSrcFacebook: "/img/seo/share-FB-big.png"
socialImageSrcFacebookWidth: "630"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#tickets", text: "Entradas"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/#aboutSDC", text: "¿En qué consiste?"}
 - {permalink: "/schedule", text: "Agenda"}
 - {permalink: "/#location-map", text: "¿Dónde?"}
 - {permalink: "/#partners", text: "Organizan"}
 - {permalink: "/cod/", text: "CoC"}

# Hero Block
heroImage: "hero.jpg"
heroMain: "Sevilla Developers Conf 4 #SVQDC"
heroTitle: "Porque aquí <b>se hacen muchas</b> cosas de <typeout>"
eventDate: "Sábado, 13 de Mayo, 2017"
typeoutTextValues: '"TensorFlow", "Java", "Go", "Microservicios", "PHP", "Swift", "Ruby", "JavaScript", "Python", "WordPress", "Xamarin", ".NET", "Kotlin", "Angular", "Perl", "Integración Contínua", "DevOps"'
typeoutFallback: "tecnología"
heroButtons:
   - {permalink: "/#tickets", text: "Consigue tu entrada"}
#   - {permalink: "/schedule", text: "Ya tenemos charlas!"}


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 5
rockstarSpeakersTitle: "Nuestros ponentes"
rockstarSpeakersButtonText: "Más información"

# Speakers List Block
showSessions: true

# Location Block
locationBlockTitle: "Dónde?"
eventLocationName: "Escuela de Organización Industrial Andalucía"
eventLocationLink: "https://www.eoi.es/es/eoi-sevilla"
eventStreetAddress: "Calle Leonardo da Vinci, 12"
eventAddressLocality: "Isla de la Cartuja"
eventAddressLocalityRegion: "Sevilla"
eventPostalCode: "41092"
eventAddressCountry: "España"
eventStartTime: "2017-05-13T09:00"
eventDoorTime: "08:00"
eventEndTime: "2017-05-13T18:00"
readableDate: "Sábado 13 de Mayo 2017"
eventPlaceCoordinates: "37.404639,-6.0087697"
mapCenterCoordinates: "37.404639,-6.0087697"
mapMobileCenterCoordinates: "37.404639,-6.0087697"
locationTbc: "Por confirmar"

# Partners Block
organizersTitle: "Organizan"
partnersTitle: "Patrocinan"
partnersC4sponsorsButton: "Únete a nosotros"
c4sponsorsUrl: "https://www.facebook.com/groups/sevilladevelopers/"

# Tickets Block
tweetsFeedImage: "twitter-feed.png"
ticketsTitle: "Entradas"
ticketsTitle2: "Desglose de las Entradas"
ticketsInfo: "Al precio de las entradas hay que añadirle las comisiones de Ticketea. Todas las entradas incluyen el legendario almuerzo de la edición anterior, WOHOOOOOOO"
ticketsOffers:

-
  name: "Community"
  price: "12"
  priceCurrency: "EUR"
  ticketsNumber: "20"
  buyButtonLink: "https://www.ticketea.com/entradas-charla-sevilladevelopers-conf-4/"
  buyButtonText: "Apoya a la comunidad"
  additionalInfo: "Al comprar esta entrada, estas permitiendo que otra persona que no se lo puede permitir acceda a la conferencia."
  additionalInfo2: {permalink: "/blog/communityTickets", text: "Más info."}
  ticketContentList: [ "Porque la comunidad es genial.", "Para que nadie se quede sin venir.", {permalink: "/blog/communityTickets", text: "Más info."}]
  validFrom: "2017-04-25T00:00"
  validThrough: "2017-05-02T23:59"
#  featured: true
  soldOut: false
  soldOutText: "Agotadas!"
#  featured: false
  ribbon: "Community"

-
  name: "BITNAMI"
  price: "6"
  priceCurrency: "EUR"
  ticketsNumber:
  buyButtonLink: "https://www.ticketea.com/entradas-charla-sevilladevelopers-conf-4/"
  buyButtonText: "Aprovecha!"
  additionalInfo: ""
  ticketContentList: [ "Gracias a Bitnami.", "Son las últimas.", "Hasta fin de existencias."]
  disabled: false
  validFrom: "2017-05-4T00:00"
  validThrough: "2017-05-11T23:59"
  soldOut: false
  soldOutText: "Agotadas!"
  ribbon: "Bitnami"
  featured: true

-
  name: "Early Bird"
  price: "6"
  priceCurrency: "EUR"
  ticketsNumber:
  buyButtonLink: "https://www.ticketea.com/entradas-charla-sevilladevelopers-conf-4/"
  buyButtonText: "Aprovecha!"
  additionalInfo: ""
  ticketContentList: [ "Luego te arrepientes.", "Descuentazo.", "¡Sólo hasta el 2 de Mayo!."]
  validFrom: "2017-04-25T00:00"
  validThrough: "2017-05-02T23:59"
  soldOut: true
  soldOutText: "Agotadas!"
  ribbon: "EOI"

# Footer
socialLinks:
 - {link: "https://twitter.com/search?q=%23SVQDC", icon: "twitter"}
 - {link: "https://www.facebook.com/groups/sevilladevelopers/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Enlaces"
  links:
   - {link: "http://www.meetup.com/PHP-Sevilla", text: "PHP Sevilla"}
   - {link: "http://http://www.meetup.com/SVQJUG", text: "SVQ JUG"}
   - {link: "https://plus.google.com/117186888160178861350/", text: "GDG Sevilla"}
   - {link: "http://nscoder-sev.tumblr.com/", text: "NSCoder Night Sevilla"}
   - {link: "https://www.meetup.com/es-ES/Geoinquietos-Sevilla/", text: "GeoInquietos"}
   - {link: "https://www.meetup.com/es-ES/Ping-a-mujeres-programadoras/", text: "Ping a Programadoras"}
 -
  title: "Contactar"
  links:
   - {link: "mailto:contacto@sevilladevelopers.com", text: "contacto@sevilladevelopers.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conducta"}

 -
  title: "Ediciones previas"
  links:
   - {link: "http://old.sevilladevelopers.com/sdc1", text: "Primera edición"}
   - {link: "http://old.sevilladevelopers.com/sdc2", text: "Segunda edición"}
   - {link: "http://old.sevilladevelopers.com/", text: "Tercera edición"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: false
discusShortName: "sdc4"

# About
aboutBlockTitle: "¿Qué es SevillaDeveloperConf?"
aboutCatch: "Este evento de eventos nace desde el grupo de <a href='https://www.facebook.com/groups/sevilladevelopers/'>SevillaDevelopers en Facebook</a>
            como una iniciativa para fomentar tanto las distintas comunidades tecnológicas de Sevilla como también para darnos oportunidad de, durante un día, ver cómo resuelven sus
            retos en otras plataformas o lenguajes."
aboutIt: "Un solo track para poder aprovechar al máximo las conversaciones entre desarrolladores y desarrolladoras de distintas áreas."


# Logistics Find Way Block
findWayTitle: "Cómo llegar"
findWayDistance: "Distancia"
findWayDriving: "En Coche"
findWayWalking: "Andando"
findWayBicycling: "En Bicicleta"
findWayTransit: "Autobus"
logisticsMapCenterCoordinates: "40.121684,-8.203308"
logisticsMapMobileCenterCoordinates: "40.121684,-8.203308"
logisticsMapAutoDirections: false